/**
 * The Capability Token provider on a real mount (Epic P2-02 must[1], must[3];
 * §12.69, §12.70).
 *
 * These cases exist because P2-02's sign-off was WITHDRAWN over precisely what
 * they check. The definition, the attenuation and `assertTokenPresented` were
 * all complete and tested, and none of them ran on any launched profile:
 * nothing issued a token and nothing armed the requirement. So the assertions
 * here are deliberately about REACH rather than about the decisions, which
 * P2-02's Contract stage already proved — a case that minted a token by hand
 * and checked it verified would pass in the world the withdrawal was about.
 *
 * The signing key is generated by `createTrustKernel` into module-private
 * state keyed by the signature-roots handle, so no test fixture holds one and
 * nothing here can read it (§12.70).
 */
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Context } from '@deepseek-ai/cordis'
import { afterEach, describe, expect, it } from 'vitest'
import AgentRegistry from '@deepseek-ai/dsh-agent'
import AgentLoop from '@deepseek-ai/dsh-agent-loop'
import LlmRuntime from '@deepseek-ai/dsh-llm'
import SessionStore, { SessionId } from '@deepseek-ai/dsh-session'
import SessionProjectionRegistry from '@deepseek-ai/dsh-session-projection'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import ToolRuntime, { defineContentToolFixture } from '@deepseek-ai/dsh-tools'
import { createTrustKernel, pinTrustKernel } from '@deepseek-ai/dsh-trust-kernel'
import { brandString } from '@deepseek-ai/dsh-brand'
import { digestToken } from '@deepseek-ai/dsh-capability-token'
import type { CapabilityTokenNonce } from '@deepseek-ai/dsh-capability-token'
import type { SignedCapabilityToken } from '@deepseek-ai/dsh-capability-token'
import CapabilityTokenFilePlugin from '@deepseek-ai/dsh-capability-token-file/src/index.ts'

const roots: string[] = []
const mounted: Context[] = []

afterEach(async () => {
  for (const ctx of mounted.splice(0)) await ctx.fiber.dispose()
  for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true })
})

const testSignal = new AbortController().signal

/** Mount the provider over a real Trust Kernel and tool runtime. */
async function mount(requireForTools: boolean, reuseDirectory?: string): Promise<{ ctx: Context; directory: string }> {
  // `reuseDirectory` mounts a SECOND provider over an existing store, which is
  // how a process restart is observed: same durable state, nothing carried
  // over in memory.
  const directory = reuseDirectory ?? await mkdtemp(join(tmpdir(), 'dsh-cap-token-'))
  if (reuseDirectory === undefined) roots.push(directory)
  const ctx = new Context()
  pinTrustKernel(ctx, createTrustKernel())
  await ctx.plugin(SessionStore)
  await ctx.plugin(SessionProjectionRegistry)
  await ctx.plugin(SystemPrompt, { persona: '' })
  await ctx.plugin(ToolRuntime)
  await ctx.plugin(LlmRuntime)
  await ctx.plugin(AgentRegistry)
  await ctx.plugin(AgentLoop, { agents: [] })
  ctx.tools.register(defineContentToolFixture({
    name: 'read_file',
    description: 'a tool the session token authorizes',
    parameters: {},
    async execute() { return [{ type: 'text', text: 'ok' }] },
  }))
  await ctx.plugin(CapabilityTokenFilePlugin, { directory, requireForTools, sessionTokenTtlMs: 60_000 })
  mounted.push(ctx)
  return { ctx, directory }
}

describe('P2-02 must[1]: a session start ISSUES a root token', () => {
  it('issues one per session, signed by the mounted Trust Kernel', async () => {
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('issue-session') })

    const token = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(token).toBeDefined()
    expect(token?.token.subject).toBe('issue-session')
    // The verb is the one a tool call demands. A token signed with any other
    // string would be recorded and then refused at every call — a failure that
    // looks like the gate working.
    expect(token?.token.verbs).toEqual(['call'])
    expect(token?.token.resources).toContain('read_file')
    await handle.dispose()
  })

  it('drops the session token when the session ends, so it cannot be replayed after', async () => {
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('ends-session') })
    expect(await ctx.capabilityTokens.whenSessionToken(handle.agent.id)).toBeDefined()
    await handle.dispose()
    expect(ctx.capabilityTokens.sessionToken(handle.agent.id)).toBeUndefined()
  })
})

describe('P2-02 must[3]: the tool requirement is ARMED, not merely registered', () => {
  it('REFUSES a tool call presenting no token once the provider armed it', async () => {
    // The negative control, and the case the withdrawal turned on: before this
    // provider existed, `requireCapabilityToken` was registered by nobody and
    // an unauthorized call ran normally.
    const { ctx } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('armed-session') })
    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c1' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
    })

    expect(result.isError).toBe(true)
    expect(JSON.stringify(result.content)).toContain('capability token')
    await handle.dispose()
  })

  it('ADMITS the same call when the session token is presented', async () => {
    // The positive control. Without it the refusal above would pass against a
    // provider that refused everything, which would break every shipped profile.
    const { ctx } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('admit-session') })
    const token = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(token).toBeDefined()

    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c2' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
      ...token === undefined ? {} : { capabilityToken: token },
    })

    expect(result.isError).toBe(false)
    await handle.dispose()
  })

  it('does NOT arm the requirement when the profile did not ask for it', async () => {
    // `requireForTools` is a validated field rather than a constant, so a
    // composition that issues and audits without yet enforcing is a real
    // arrangement. This pins that the flag is what decides.
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('unarmed-session') })
    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c3' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
    })

    expect(result.isError).toBe(false)
    await handle.dispose()
  })
})

describe('P2-02 must[3]: a tool registered LATE is still callable', () => {
  it('re-issues so a tool that appears after the first call is authorized', async () => {
    // Not hypothetical: `dsh-tool-subagent` is mounted twice in `bundle/base`
    // and registers its tool from a `subagent/provider-added` listener, which
    // can fire after the session's first tool call. A single mint at session
    // start refused that tool for the rest of the session — a permanent denial
    // of a legitimate tool, which is the withdrawal's failure inverted.
    const { ctx } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('late-session') })
    const first = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(first?.token.resources).not.toContain('write_file')

    ctx.tools.register(defineContentToolFixture({
      name: 'write_file',
      description: 'registered after the session already held a token',
      parameters: {},
      async execute() { return [{ type: 'text', text: 'ok' }] },
    }))

    const reissued = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(reissued?.token.resources).toContain('write_file')
    // The point is the CALL, not the resource list: a token listing the name
    // but refused at dispatch would pass the assertion above and still break.
    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c4' as never,
      name: 'write_file',
      arguments: {},
      agent: handle.agent,
      ...reissued === undefined ? {} : { capabilityToken: reissued },
    })
    expect(result.isError).toBe(false)
    await handle.dispose()
  })

  it('does not re-sign when the visible tools have not grown', async () => {
    // Re-issue is growth-triggered, not per-call: a signature on every dispatch
    // would be invisible here except as cost.
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('stable-session') })
    const first = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    const again = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(again).toBe(first)
    await handle.dispose()
  })
})

describe('P2-02 acceptance[1]: revocation survives a re-issue', () => {
  it('kills a child derived from an EARLIER root when the session is revoked', async () => {
    // Re-issue mints an unrelated root (`issueToken` fixes `parentDigest` to
    // null), so a child derived before the growth event has no lineage to the
    // newest root. Revoking that newest root alone would leave this child
    // running — acceptance[1] failing silently on exactly the sessions that
    // grew a tool. Revocation is per session for that reason.
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('revoke-session') })
    const firstRoot = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(firstRoot).toBeDefined()

    // Reached through the concrete plugin, not the service contract: the
    // contract publishes only what a CONSUMER needs, and no production consumer
    // attenuates or reads revocation state — putting `service` on it would be
    // a public surface with no current owner.
    const provider = ctx.get('capabilityTokens') as CapabilityTokenFilePlugin
    const child = await provider.service.attenuate(firstRoot!, {
      subject: firstRoot!.token.subject,
      resources: ['read_file'],
      verbs: ['call'],
      expiresAt: firstRoot!.token.expiresAt,
      constraints: {},
      nonce: brandString<CapabilityTokenNonce>('0123456789abcdef0123456789abcdef'),
    })
    expect(child.accepted).toBe(true)

    // Grow the visible tools so the next read mints a SECOND, unrelated root.
    ctx.tools.register(defineContentToolFixture({
      name: 'grow_tool',
      description: 'forces a re-issue',
      parameters: {},
      async execute() { return [{ type: 'text', text: 'ok' }] },
    }))
    const secondRoot = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(secondRoot).not.toBe(firstRoot)

    await ctx.capabilityTokens.revokeSession(handle.agent.id)

    // The child of the FIRST root must be dead, not just the newest root.
    const childDigest = digestToken((child as { child: SignedCapabilityToken }).child.token)
    expect(provider.service.isRevoked(childDigest)).toBe(true)
    await handle.dispose()
  })
})

describe('P2-02 acceptance[2]: the durable store holds no raw secret', () => {
  it('writes tokens to disk without ever writing a signing key', async () => {
    const { ctx, directory } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('persist-session') })
    // The store is written through the service; force a save by recording the
    // issuance, then read the file back as bytes.
    await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    const text = await readFile(join(directory, 'capability-tokens.json'), 'utf8')

    expect(text).toContain('persist-session')
    // The private key lives in `createTrustKernel`'s module-private state,
    // keyed by the signature-roots handle, so there is no path by which it
    // could reach this file — asserted rather than assumed, because a future
    // change that put the key on the handle would be invisible otherwise.
    expect(text).not.toContain('PRIVATE KEY')
    expect(text).not.toContain('privateKey')
    await handle.dispose()
  })
})

describe('P4-09 must[2]: a session stays revocable after it ends, and revocation stays precise', () => {
  it('revokes a DISPOSED session\'s authority, and the revoked token is refused AT THE CALL', async () => {
    // The case a detached run makes ordinary rather than exceptional: the
    // launcher is gone by the time anyone asks. `sessionRoots` is dropped at
    // `agent/disposed`, so the previous implementation iterated an empty list
    // and reported success having revoked nothing.
    //
    // Observed at the dispatch rather than by asking the provider whether it
    // thinks the token is revoked: a recorded revocation that the tool call
    // still honours is the gap between a decision and its enforcement.
    const { ctx } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('revoke-after-end') })
    const token = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(token).toBeDefined()
    await handle.dispose()

    expect(await ctx.capabilityTokens.revokeSession(SessionId('revoke-after-end'))).toBe('revoked')

    const refused = await ctx.tools.execute({
      signal: testSignal,
      callId: 'revoked-call' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
      ...token === undefined ? {} : { capabilityToken: token },
    })
    expect(refused.isError).toBe(true)
  })

  it('revokes it from a NEW provider instance over the same store, so a restart does not lose the ability', async () => {
    // Durable or not is the whole question: an index rebuilt only in memory
    // answers correctly until the process that built it goes away, which is
    // exactly when a detached run is still running.
    const { ctx, directory } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('revoke-after-restart') })
    await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    await handle.dispose()
    await ctx.fiber.dispose()

    const { ctx: restarted } = await mount(true, directory)

    expect(await restarted.capabilityTokens.revokeSession(SessionId('revoke-after-restart'))).toBe('revoked')
  })

  it('leaves ANOTHER session of the same principal untouched', async () => {
    // The precision control, and the case a subject-derived index could not
    // pass: `subject` is the principal, so matching on it would revoke every
    // session that principal holds.
    const { ctx } = await mount(true)
    const kept = await ctx.agents.create({ sessionId: SessionId('sibling-kept') })
    const revoked = await ctx.agents.create({ sessionId: SessionId('sibling-revoked') })
    const keptToken = await ctx.capabilityTokens.whenSessionToken(kept.agent.id)
    await ctx.capabilityTokens.whenSessionToken(revoked.agent.id)

    await ctx.capabilityTokens.revokeSession(SessionId('sibling-revoked'))

    expect(await ctx.capabilityTokens.whenSessionToken(kept.agent.id)).toStrictEqual(keptToken)
    await kept.dispose()
    await revoked.dispose()
  })

  it('reports `nothing-to-revoke` for a session no root was ever issued for', async () => {
    // Distinct from success on purpose. Reporting plain success here tells an
    // operator their revocation took effect when it had nothing to act on.
    const { ctx } = await mount(true)

    expect(await ctx.capabilityTokens.revokeSession(SessionId('never-existed'))).toBe('nothing-to-revoke')
  })
})
