/**
 * The Capability Token provider on a real mount (Epic P2-02 must[1], must[3];
 * §12.69, §12.70).
 *
 * These cases exist because P2-02's sign-off was WITHDRAWN over precisely what
 * they check. The definition, the attenuation and `assertTokenPresented` were
 * all complete and tested, and none of them ran on any launched profile:
 * nothing issued a token and nothing armed the requirement. So the assertions
 * here are deliberately about REACH rather than about the decisions, which
 * P2-02's Contract stage already proved — a case that minted a token by hand
 * and checked it verified would pass in the world the withdrawal was about.
 *
 * The signing key is generated by `createTrustKernel` into module-private
 * state keyed by the signature-roots handle, so no test fixture holds one and
 * nothing here can read it (§12.70).
 */
import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { Context } from '@deepseek-ai/cordis'
import { afterEach, describe, expect, it } from 'vitest'
import AgentRegistry from '@deepseek-ai/dsh-agent'
import AgentLoop from '@deepseek-ai/dsh-agent-loop'
import LlmRuntime from '@deepseek-ai/dsh-llm'
import SessionStore, { SessionId } from '@deepseek-ai/dsh-session'
import SessionProjectionRegistry from '@deepseek-ai/dsh-session-projection'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import ToolRuntime, { defineContentToolFixture } from '@deepseek-ai/dsh-tools'
import { createTrustKernel, pinTrustKernel } from '@deepseek-ai/dsh-trust-kernel'
import CapabilityTokenFilePlugin from '@deepseek-ai/dsh-capability-token-file/src/index.ts'

const roots: string[] = []
const mounted: Context[] = []

afterEach(async () => {
  for (const ctx of mounted.splice(0)) await ctx.fiber.dispose()
  for (const root of roots.splice(0)) await rm(root, { recursive: true, force: true })
})

const testSignal = new AbortController().signal

/** Mount the provider over a real Trust Kernel and tool runtime. */
async function mount(requireForTools: boolean): Promise<{ ctx: Context; directory: string }> {
  const directory = await mkdtemp(join(tmpdir(), 'dsh-cap-token-'))
  roots.push(directory)
  const ctx = new Context()
  pinTrustKernel(ctx, createTrustKernel())
  await ctx.plugin(SessionStore)
  await ctx.plugin(SessionProjectionRegistry)
  await ctx.plugin(SystemPrompt, { persona: '' })
  await ctx.plugin(ToolRuntime)
  await ctx.plugin(LlmRuntime)
  await ctx.plugin(AgentRegistry)
  await ctx.plugin(AgentLoop, { agents: [] })
  ctx.tools.register(defineContentToolFixture({
    name: 'read_file',
    description: 'a tool the session token authorizes',
    parameters: {},
    async execute() { return [{ type: 'text', text: 'ok' }] },
  }))
  await ctx.plugin(CapabilityTokenFilePlugin, { directory, requireForTools, sessionTokenTtlMs: 60_000 })
  mounted.push(ctx)
  return { ctx, directory }
}

describe('P2-02 must[1]: a session start ISSUES a root token', () => {
  it('issues one per session, signed by the mounted Trust Kernel', async () => {
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('issue-session') })

    const token = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(token).toBeDefined()
    expect(token?.token.subject).toBe('issue-session')
    // The verb is the one a tool call demands. A token signed with any other
    // string would be recorded and then refused at every call — a failure that
    // looks like the gate working.
    expect(token?.token.verbs).toEqual(['call'])
    expect(token?.token.resources).toContain('read_file')
    await handle.dispose()
  })

  it('drops the session token when the session ends, so it cannot be replayed after', async () => {
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('ends-session') })
    expect(await ctx.capabilityTokens.whenSessionToken(handle.agent.id)).toBeDefined()
    await handle.dispose()
    expect(ctx.capabilityTokens.sessionToken(handle.agent.id)).toBeUndefined()
  })
})

describe('P2-02 must[3]: the tool requirement is ARMED, not merely registered', () => {
  it('REFUSES a tool call presenting no token once the provider armed it', async () => {
    // The negative control, and the case the withdrawal turned on: before this
    // provider existed, `requireCapabilityToken` was registered by nobody and
    // an unauthorized call ran normally.
    const { ctx } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('armed-session') })
    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c1' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
    })

    expect(result.isError).toBe(true)
    expect(JSON.stringify(result.content)).toContain('capability token')
    await handle.dispose()
  })

  it('ADMITS the same call when the session token is presented', async () => {
    // The positive control. Without it the refusal above would pass against a
    // provider that refused everything, which would break every shipped profile.
    const { ctx } = await mount(true)
    const handle = await ctx.agents.create({ sessionId: SessionId('admit-session') })
    const token = await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    expect(token).toBeDefined()

    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c2' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
      ...token === undefined ? {} : { capabilityToken: token },
    })

    expect(result.isError).toBe(false)
    await handle.dispose()
  })

  it('does NOT arm the requirement when the profile did not ask for it', async () => {
    // `requireForTools` is a validated field rather than a constant, so a
    // composition that issues and audits without yet enforcing is a real
    // arrangement. This pins that the flag is what decides.
    const { ctx } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('unarmed-session') })
    const result = await ctx.tools.execute({
      signal: testSignal,
      callId: 'c3' as never,
      name: 'read_file',
      arguments: {},
      agent: handle.agent,
    })

    expect(result.isError).toBe(false)
    await handle.dispose()
  })
})

describe('P2-02 acceptance[2]: the durable store holds no raw secret', () => {
  it('writes tokens to disk without ever writing a signing key', async () => {
    const { ctx, directory } = await mount(false)
    const handle = await ctx.agents.create({ sessionId: SessionId('persist-session') })
    // The store is written through the service; force a save by recording the
    // issuance, then read the file back as bytes.
    await ctx.capabilityTokens.whenSessionToken(handle.agent.id)
    const text = await readFile(join(directory, 'capability-tokens.json'), 'utf8')

    expect(text).toContain('persist-session')
    // The private key lives in `createTrustKernel`'s module-private state,
    // keyed by the signature-roots handle, so there is no path by which it
    // could reach this file — asserted rather than assumed, because a future
    // change that put the key on the handle would be invisible otherwise.
    expect(text).not.toContain('PRIVATE KEY')
    expect(text).not.toContain('privateKey')
    await handle.dispose()
  })
})
